# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - wget https://github.com/OSGeo/proj.4/releases/download/6.2.0/proj-6.2.0.tar.gz
  - tar -xzvf proj-6.2.0.tar.gz
  - cd proj-6.2.0; ./configure; make; sudo make install

addons:
  apt:
    packages:
    - libgdal-dev

r_packages:
  - covr

r_github_packages:
  - MangoTheCat/visualTest
  - jimhester/lintr
  - jimhester/covr
  - r-lib/pkgdown

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
